version: 2
jobs:
  build:
    working_directory: ~/scully-personal-website
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: scully-personal-website-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: scully-personal-website-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: |
          npm run build
      - run: |
          npm run scully -- --scanRoutes
      - persist_to_workspace:
          root: ~/scully-personal-website
          paths:
            - dist/*
  deploy:
    working_directory: ~/scully-personal-website
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa'
      - checkout
      - attach_workspace:
          at: ~/scully-personal-website
      - run:
          name: Install gh-pages
          command: |
            npm install -g --silent gh-pages
      - run:
          name: Configure git
          command: |
            git config user.email "nhvu.95@gmail.com"
            git config user.name "Vue Nguyen"
      - run:
          name: Deploy to gh-pages branch
          command: |
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/portfolio.git
            echo 'nhvu95.com' > ./dist/static/CNAME && gh-pages -d ./dist/static"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main